In [3]:
import pandas as pd

In [4]:
data ={
    'Name' : ["EeNa","Mena","Dina","Mona","Leena"],
    'Maths_score' : [85,73,None,56,77],
    'Science_score' : [None,45,77,66,89] ,
    'English_score' : [56,None,45,67,89]
}

In [5]:
df=pd.DataFrame(data)

In [6]:
df

    Name  Maths_score  Science_score  English_score
0   EeNa         85.0            NaN           56.0
1   Mena         73.0           45.0            NaN
2   Dina          NaN           77.0           45.0
3   Mona         56.0           66.0           67.0
4  Leena         77.0           89.0           89.0

In [7]:
df.isnull()

    Name  Maths_score  Science_score  English_score
0  False        False           True          False
1  False        False          False           True
2  False         True          False          False
3  False        False          False          False
4  False        False          False          False

In [8]:
df.isnull().sum()

Name             0
Maths_score      1
Science_score    1
English_score    1
dtype: int64

In [9]:
df["Maths_score"]=df["Maths_score"].fillna(df["Maths_score"].mean())

In [10]:
df["Science_score"]=df["Science_score"].fillna(df["Science_score"].mean())

In [11]:
df["Science_score"]

0    69.25
1    45.00
2    77.00
3    66.00
4    89.00
Name: Science_score, dtype: float64

In [12]:
df.columns

Index(['Name', 'Maths_score', 'Science_score', 'English_score'], dtype='object')

In [13]:
df["English_score"]=df["English_score"].fillna(df["English_score"].mean())

In [14]:
df.isnull()

    Name  Maths_score  Science_score  English_score
0  False        False          False          False
1  False        False          False          False
2  False        False          False          False
3  False        False          False          False
4  False        False          False          False

In [15]:
 def capping(column):
     q1=column.quantile(0.25)
     q3=column.quantile(0.75)
     IOR=q3-q1
     lower_limit=q1 - (1.5*IOR)
     upper_limit=q3 + (1.5*IOR)

In [16]:
numerical_columns=df.select_dtypes(include=["float64","int64"]).columns

In [17]:
for col in numerical_columns:
    capping(df[col])

In [18]:
df

    Name  Maths_score  Science_score  English_score
0   EeNa        85.00          69.25          56.00
1   Mena        73.00          45.00          64.25
2   Dina        72.75          77.00          45.00
3   Mona        56.00          66.00          67.00
4  Leena        77.00          89.00          89.00

In [19]:
df[numerical_columns]=df[numerical_columns].apply(lambda x : ((x-x.min())/(x.max()-x.min())))

In [20]:
df

    Name  Maths_score  Science_score  English_score
0   EeNa     1.000000       0.551136         0.2500
1   Mena     0.586207       0.000000         0.4375
2   Dina     0.577586       0.727273         0.0000
3   Mona     0.000000       0.477273         0.5000
4  Leena     0.724138       1.000000         1.0000